# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b321d175aff24f108da3c5dd80c75d1b8d8a427053abf217c4f62bc50047875ab2de5c9483a7e8536e9bef65e650429fe199359e9cabe45ff9174bfb44e14ae

test:
  secret_key_base: e946980d744d8be2fb6622488b42f2364f3fc42dbbb8f4de2dc69b65ff710110f6807628a3fa54695dd907b7e4c5f0e87e0482f22ec3b494d8bb6bdd3f0ff131

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
